03/15/2023 10:09:22 PM - WARNING - PyNaCl is not installed, voice will NOT be supported
03/15/2023 10:09:22 PM - INFO - logging in using static token
03/15/2023 10:09:22 PM - INFO - Shard ID None has connected to Gateway (Session ID: 73a2a5ff94db8f10f6c2c5d60899cc66).
03/15/2023 10:09:24 PM - INFO - Probot#0092 has connected to Discord!
03/15/2023 10:09:24 PM - ERROR - Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/runner/discord-bot/venv/lib/python3.10/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 26, in on_ready
    logging.info(f"{guild.name}(id: {guild.id})")
AttributeError: 'NoneType' object has no attribute 'name'
03/15/2023 10:20:09 PM - INFO - New Message from kilbot#5788: help
03/15/2023 10:20:25 PM - INFO - New Message from kilbot#5788: !
03/15/2023 10:20:25 PM - WARNING - Could not access license server. Error: HTTPSConnectionPool(host='yourapi.com', port=443): Max retries exceeded with url: /verify?key=! (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))
03/15/2023 10:20:25 PM - ERROR - Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/runner/discord-bot/venv/lib/python3.10/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 50, in on_message
    await self.verify(message, cont)
  File "bot.py", line 74, in verify
    if response.status_code == 200 and response.json()['valid']:
UnboundLocalError: local variable 'response' referenced before assignment
03/15/2023 10:20:32 PM - INFO - New Message from kilbot#5788: !hi
03/15/2023 10:20:32 PM - WARNING - Could not access license server. Error: HTTPSConnectionPool(host='yourapi.com', port=443): Max retries exceeded with url: /verify?key=!hi (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))
03/15/2023 10:20:32 PM - ERROR - Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/runner/discord-bot/venv/lib/python3.10/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 50, in on_message
    await self.verify(message, cont)
  File "bot.py", line 74, in verify
    if response.status_code == 200 and response.json()['valid']:
UnboundLocalError: local variable 'response' referenced before assignment
03/15/2023 10:24:47 PM - INFO - New Message from kilbot#5788: !
03/15/2023 10:24:47 PM - WARNING - Could not access license server. Error: HTTPSConnectionPool(host='yourapi.com', port=443): Max retries exceeded with url: /verify?key=! (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))
03/15/2023 10:24:47 PM - ERROR - Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/runner/discord-bot/venv/lib/python3.10/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 50, in on_message
    await self.verify(message, cont)
  File "bot.py", line 74, in verify
UnboundLocalError: local variable 'response' referenced before assignment
03/15/2023 10:25:12 PM - WARNING - PyNaCl is not installed, voice will NOT be supported
03/15/2023 10:25:12 PM - INFO - logging in using static token
03/15/2023 10:25:13 PM - INFO - Shard ID None has connected to Gateway (Session ID: 2c6ed00d73ba3119dbc8fbcb9e6325ae).
03/15/2023 10:25:15 PM - INFO - Probot#0092 has connected to Discord!
03/15/2023 10:25:15 PM - INFO - WooCommerce POS(id: 711884517081612298)
03/15/2023 10:25:26 PM - INFO - New Message from kilbot#5788: !
03/15/2023 10:25:27 PM - WARNING - Could not access license server. Error: HTTPSConnectionPool(host='yourapi.com', port=443): Max retries exceeded with url: /verify?key=! (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))
03/15/2023 10:25:27 PM - ERROR - Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/runner/discord-bot/venv/lib/python3.10/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 50, in on_message
    await self.verify(message, cont)
  File "bot.py", line 75, in verify
    if response.status_code == 200 and response.json()['valid']:
AttributeError: 'NoneType' object has no attribute 'status_code'
03/15/2023 10:26:39 PM - INFO - New Message from kilbot#5788: hello
03/15/2023 10:26:46 PM - INFO - New Message from kilbot#5788: help
03/15/2023 10:33:52 PM - INFO - New Message from kilbot#5788: !
03/15/2023 10:33:52 PM - WARNING - Could not access license server. Error: HTTPSConnectionPool(host='yourapi.com', port=443): Max retries exceeded with url: /verify?key=! (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))
03/15/2023 10:33:52 PM - ERROR - Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/runner/discord-bot/venv/lib/python3.10/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 50, in on_message
    await self.verify(message, cont)
  File "bot.py", line 75, in verify
    return
AttributeError: 'NoneType' object has no attribute 'status_code'
03/15/2023 10:33:58 PM - INFO - New Message from kilbot#5788: !hkhj
03/15/2023 10:33:58 PM - WARNING - Could not access license server. Error: HTTPSConnectionPool(host='yourapi.com', port=443): Max retries exceeded with url: /verify?key=!hkhj (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))
03/15/2023 10:33:58 PM - ERROR - Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/runner/discord-bot/venv/lib/python3.10/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 50, in on_message
    await self.verify(message, cont)
  File "bot.py", line 75, in verify
    return
AttributeError: 'NoneType' object has no attribute 'status_code'
03/15/2023 10:34:30 PM - WARNING - PyNaCl is not installed, voice will NOT be supported
03/15/2023 10:34:30 PM - INFO - logging in using static token
03/15/2023 10:34:30 PM - INFO - Shard ID None has connected to Gateway (Session ID: 8c09cbd0f0b82ffa55ec2edff62a8fee).
03/15/2023 10:34:32 PM - INFO - Probot#0092 has connected to Discord!
03/15/2023 10:34:32 PM - INFO - WooCommerce POS(id: 711884517081612298)
03/15/2023 10:34:42 PM - INFO - New Message from kilbot#5788: !ff
03/15/2023 10:34:42 PM - WARNING - Could not access license server. Error: HTTPSConnectionPool(host='yourapi.com', port=443): Max retries exceeded with url: /verify?key=!ff (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:997)')))
